### ISSUE TITLE
Release version 0.2.1

### ISSUE THREAD

**Issue by adngdb** [asvd/jailed#28]
Hi! It's been more than a year since a release was tagged, and I guess that means what's available on npm is not up-to-date? So, would it be possible to tag a new release? 

Thanks,
Adrian

**Comment by asvd** [comment]
I'm currently preparing the new release actually. Going to finish the new demo, and update the docs. Should hopefully be done until the next weekend (or the one after)

**Comment by asvd** [comment]
0.3.0 released
