### ISSUE TITLE
Potential issue with Jailed crashing tab in travis

### ISSUE THREAD

**Issue by dtracers** [asvd/jailed#30]
https://travis-ci.org/dtracers/coursesketch/builds/121328585

I am creating chrome in travis (which for some reason has to run without sandbox) and as a result it sometimes crashes the chrome tab causing my build to fail.

I believe the problem is jailed because this is the only library I'm using in the tests that are crashing.

(and unfortunately this is the only real stack trace I have)
```
[INFO]   2) running test for /test/utilities/functions/baseExceptionTest.html?coverage=true
[INFO] childScriptTest.js
[INFO] 03:20:23.738 INFO - Executing: [get: http://localhost:9001/test/utilities/functions/childScriptTest.html?coverage=true])
[INFO] 03:20:29.082 WARN - Exception thrown
[INFO] org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
[INFO] from tab crashed
```

**Comment by asvd** [comment]
okaay...

can you maybe reproduce it outside of travis / selenium somehow? like manually repeat the same steps?

**Comment by dtracers** [comment]
I updated to the latest version (using the latest commit) and it seems to be working better so I think the merges after 0.2.0 have fixed it or at least made it more stable.

I will do more testing and reopen it if I can reproduce it using manual testing
